<?php
session_start();
?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>WebTech - XML </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/style.css" rel="stylesheet">

</head>

<body>
    <!-- Topbar Start -->
    <!-- Topbar End -
     Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-9">
                    <a href="index.php"><h1 class="m-0"><span class="text-primary">Web</span>Tech</h1></a><br>
                    <h2 class="m-0">eXtensible Markup Language(XML) </h2><br>
                    <div class="row justify-content-center  hackerFont ">
                        <div class="col-md-10">
                            <ul>
                                <li>XML is a cross-platform, software and hardware independent tool for transmitting information.</li>
                                <li>XML is a portable, widely supported, open technology for data storage and exchange</li>
                                <li>Developed from SGML (Standard Generalised Markup Language )</li>
                                <li>Became a W3C Recommendations in 1998</li>
                                <li>A meta-markup language</li>
                                <li>XML can be written by hand or generated by computer
                                    –Useful for data exchange</li>
                                <li>Foundation
                                    for
                                    several
                                    next-generation
                                    technologies:<br>
                                    –RSS, AJAX, Web Services, etc.</li>
                                <li>Tags are not predefined (user generated)</li>
                            </ul>
                            <h5 class="bold color_white pt-3">
                                What does XML do?
                            </h5>
                            <ul>
                                <li>XML is used to structure and describe information.</li>
                                <li>Intended to be used with the Internet</li>
                                <li>Used to facilitate sharing between different systems data</li>
                                
                            </ul>
                            <h5 class="bold color_white pt-3">
                                Smart processing using XMl
                            </h5>
                            <ul>
                                <li>>COMPUTER> and >SPECIFICATIONS> provide logical containers for extracting and manipulating product information as a unit</li>
                            </ul>
                            <h5 class="bold color_white pt-3">
                                Document exchange
                            </h5>
                            <li>Use of XMl allows companies to
                                exchange information that can be
                                processed automatically without
                                human intervention e.g.<br>– Purchase orders<br>
                                – Invoices<br>
                                – Catalogues etc</li>
                            <h5 class="bold color_white pt-3">
                                Document exchange
                            </h5>
                            <li>XML was designed to carry data.</li>
                            <li>XML is not a replacement for HTML.</li>
                            <li>XML and HTML were designed with different goals:<br>XML was designed to describe data and to focus on
                                what data is.<br>
                                •HTML was designed to display data and to focus on
                                how data looks.<br>
                                •HTML is about displaying information, while XML is
                                about describing information.<br></li>
                        </div>
                    </div>
            </div>
        </div>
        <div class="container-fluid bg-dark text-white py-5 px-sm-3 px-lg-5" style="margin-top: 90px;">
            <div class="row pt-5">
                <div class="col-lg-7 col-md-12">
                    <div class="row">
                        <div class="col-md-6 mb-5">
                            <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Get In Touch</h5>
                            <p><i class="fa fa-map-marker-alt mr-2"></i>123 Street, Khartoum, Sudan</p>
                            <p><i class="fa fa-phone-alt mr-2"></i>+249 991 877454</p>
                            <p><i class="fa fa-envelope mr-2"></i>ahmedmostafaomer@gmail.com</p>
                            
                        </div>
                        <div class="col-md-6 mb-5">
                            <h5 class="text-primary text-uppercase mb-4" style="letter-spacing: 5px;">Our Courses</h5>
                            <div class="d-flex flex-column justify-content-start">
                                <a class="text-white mb-2" href="sessions.php"><i class="fa fa-angle-right mr-2"></i>PHP Sessions and Cookies</a>
                                <a class="text-white mb-2" href="upload.php"><i class="fa fa-angle-right mr-2"></i>File Upload</a>
                                <a class="text-white mb-2" href="ajax.php"><i class="fa fa-angle-right mr-2"></i>AJAX Technology</a>
                                <a class="text-white mb-2" href="ajax.php"><i class="fa fa-angle-right mr-2"></i>PHP with AJAX</a>
                                <a class="text-white" href="xml.php"><i class="fa fa-angle-right mr-2"></i>XML Technologies</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</body>
</html>
<?php echo "<style>*{background-color:" . $_SESSION["theme"] . ";}</style>"; ?>